a = int(input("Ввеите число/t"))
b = int(input("Введите число/t "))
print((a-b)*(a+b))
print(a**2-2*a*b+b**2)
print(a**2+2*a*b+b**2)
print(a**2-3*a**2*b-3*a*b**2-b*3**2)
print(a**3+3*a**2*b+3*a*b**2+b**3)
print((a+b)*(a**2-a*b+b**2))
print((a-b)*(a**2+a*b+b**2))
